### PR TITLE
Create slightly better tank drive

### PR DESCRIPTION
**Pull request by hmsrothman**
This should have turning

### CODE REVIEW

**Comment by wffirilat** [comment]
I don't like that tank drive code. maybe something like how quad-copters work? its like summing the motor speeds for the different behaviors

**Comment by hmsrothman** [comment]
i don't quite understand what you're saying

**Comment by wffirilat** [comment]
its a little weird. something like:
        public void teleopPeriodic() {
            double x = stick.getX();
            double y = stick.getY();
            double r = Math.sqrt(x \* x + y \* y);
            float right_fw = stick.getY();
            float left_fw = stick.getY();
            float right_toTurn = stick.getX();
            float left_toTurn = -stick.getX();
            robot.setLeftRightMotorOutputs(left_fw + left_toTurn, right_fw + right_toTurn);
        }

**Comment by hmsrothman** [comment]
i was thinking of doing something like that, the problem is that you run the risk of leaving the -1 to 1 range of the motor controller. I thought it made more sense to do something with polar(ish) coordinates

**Comment by wffirilat** [comment]
i think it would be better to clamp them than try to figure out polar coords

**Comment by hmsrothman** [comment]
then you'd run into some unexpected behavior i think.
My method has one motor on at the level of the stick, while the other one uses cos(2theta). this should work so that at theta=90 degrees, its the same as going forward, at theta=45 degrees it's not moving while the other one is going, and at theta = 0degrees, it's going backwards for maximum turnage

**Comment by wffirilat** [comment]
yeah okay. i've just had bad experiences with trig in roboting... mostly it's always just a little more complicated than you think

**Comment by hmsrothman** [comment]
could be. Im almost positive i got the signs wrong, but thats just a matter of adding some negative signs in the right places with some trial and error

**Comment by wffirilat** [comment]
call it good then

**Comment by hmsrothman** [comment]
cool

**Comment by hmsrothman** [comment]
how's the wiring going? are you guys actually able to test it?

**Comment by hmsrothman** [comment]
and what other code do you want?

**Comment by wffirilat** [comment]
... im not there either

**Comment by hmsrothman** [comment]
oh. lol

**Comment by wffirilat** [comment]
the others must not know

**Comment by hmsrothman** [comment]
k

**Comment by wffirilat** [comment]
delete the evidence

**Comment by hmsrothman** [comment]
which evidence?

**Comment by wffirilat** [comment]
exactly

**Comment by hmsrothman** [comment]
right

**Pull request merged**
